# ===============================
# APPLICATION
# ===============================
spring.application.name=AccountsReceivableService
spring.task.scheduling.enabled=true

# ===============================
# DATASOURCE (AR Database - Aiven)
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# EXTERNAL SERVICES
# ===============================
tms.api.base-url=${TMS_API_BASE_URL}

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.AccountReceivableManagement=DEBUG
logging.level.io.debezium=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.apache.kafka.connect=WARN



# ===============================
# CLIENT CDC (RMS -> AR)
# ===============================

client-cdc.enabled=true




# Connector
client-cdc.connector-name=RMS
client-cdc.connector-class=io.debezium.connector.mysql.MySqlConnector

# Source Database (RMS RDS)
client-cdc.database-type=mysql
client-cdc.hostname=${RMS_DB_HOST}
client-cdc.port=${RMS_DB_PORT}
client-cdc.database-name=${RMS_DB_NAME}
client-cdc.username=${RMS_DB_USERNAME}
client-cdc.password=${RMS_DB_PASSWORD}

client-cdc.jdbc-url=jdbc:mysql://${RMS_DB_HOST}:${RMS_DB_PORT}/${RMS_DB_NAME}?connectionTimeZone=UTC

# Debezium
client-cdc.server-name=rms_mysql
client-cdc.server-id=85744
client-cdc.topic-prefix=client-cdc

# Monitor only the RMS database
client-cdc.database-include-list=rms

# Monitor only the client table
client-cdc.table-include-list=rms.client

# Snapshot
client-cdc.snapshot-mode=when_needed

# Storage
client-cdc.offset-table=debezium_client_offsets
client-cdc.schema-history-table=debezium_client_schema_history

# SSL
client-cdc.ssl.mode=REQUIRED

# ===============================
# PROJECT CDC (PMS -> AR)
# ===============================

project-cdc.enabled=true

# Connector
project-cdc.connector-name=PMS
project-cdc.connector-class=io.debezium.connector.mysql.MySqlConnector

# Source Database (PMS RDS - Shared Dev RDS)
project-cdc.database-type=mysql
project-cdc.hostname=${PMS_DB_HOST}
project-cdc.port=${PMS_DB_PORT}
project-cdc.database-name=${PMS_DB_NAME}
project-cdc.username=${PMS_DB_USERNAME}
project-cdc.password=${PMS_DB_PASSWORD}

project-cdc.jdbc-url=jdbc:mysql://${PMS_DB_HOST}:${PMS_DB_PORT}/${PMS_DB_NAME}?connectionTimeZone=UTC
# Debezium
project-cdc.server-name=pms_mysql
project-cdc.server-id=85745
project-cdc.topic-prefix=project-cdc

# Monitor only the PMS database
project-cdc.database-include-list=pms

# Monitor only the project table
project-cdc.table-include-list=pms.projects

# Snapshot
project-cdc.snapshot-mode=when_needed

# Storage
project-cdc.offset-table=debezium_project_offsets
project-cdc.schema-history-table=debezium_project_schema_history

# SSL
project-cdc.ssl.mode=REQUIRED